name: Deploy to Pages

on:
  push:
    branches: main

  workflow_dispatch:

concurrency:
  group: gh-pages-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build static site

    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build static export
        run: npm run build

      - name: Upload build files
        uses: actions/upload-artifact@v3
        with:
          path: ./out
          name: github-pages

  deploy:
    name: Deploy to Pages
    needs: build
    permissions:
      pages: write
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v2
