name: Deploy to Pages

on:
  push:
    branches: main

  workflow_dispatch:

concurrency:
  group: gh-pages-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build static site

    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            .next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-

      - name: Install dependencies
        run: npm ci

      - name: Build static export
        run: npm run build

      - name: Upload build files
        uses: actions/upload-artifact@v1
        with:
          path: ./out
          name: github-pages

  deploy:
    name: Deploy to Pages
    needs: build
    permissions:
      pages: write
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v2
